# Phase II: Experimental Evaluation

## 1. Load Experimental Results

In [1]:
import pandas as pd

improved_lcs_results = pd.read_csv(
    "../results/improved_lcs/improved_lcs_metrics.csv"
)

model_comparison_results = pd.read_csv(
    "../results/model_comparison/model_comparison_results.csv"
)

print("Files loaded successfully.")

Files loaded successfully.

In [2]:
print("Improved eLCS Results")
display(improved_lcs_results)

print("\nModel Comparison Results")
display(model_comparison_results)

Improved eLCS Results

              Metric  Improved eLCS
0           Accuracy       0.768630
1          Precision       0.541522
2             Recall       0.836898
3           F1 Score       0.657563
4  Balanced Accuracy       0.790430

Model Comparison Results

,Model,Accuracy,Precision,Recall,F1 Score,Balanced Accuracy
0,Improved eLCS,0.768630,0.541522,0.836898,0.657563,0.790430
1,Logistic Regression,0.739532,0.505942,0.796791,0.618899,0.757816
2,Decision Tree,0.761533,0.551913,0.540107,0.545946,0.690826
3,Random Forest,0.836054,0.703704,0.660428,0.681379,0.779972

## 2. Consolidated Performance Comparison

In [7]:
model_comparison_results

,Model,Accuracy,Precision,Recall,F1 Score,Balanced Accuracy
0,Improved eLCS,0.768630,0.541522,0.836898,0.657563,0.790430
1,Logistic Regression,0.739532,0.505942,0.796791,0.618899,0.757816
2,Decision Tree,0.761533,0.551913,0.540107,0.545946,0.690826
3,Random Forest,0.836054,0.703704,0.660428,0.681379,0.779972

In [8]:
consolidated_comparison = (
    model_comparison_results
    .sort_values(
        by="F1 Score",
        ascending=False
    )
    .reset_index(drop=True)
)

consolidated_comparison

,Model,Accuracy,Precision,Recall,F1 Score,Balanced Accuracy
0,Random Forest,0.836054,0.703704,0.660428,0.681379,0.779972
1,Improved eLCS,0.768630,0.541522,0.836898,0.657563,0.790430
2,Logistic Regression,0.739532,0.505942,0.796791,0.618899,0.757816
3,Decision Tree,0.761533,0.551913,0.540107,0.545946,0.690826

## 3. Model Ranking

In [3]:
accuracy_ranking = (
    model_comparison_results
    .sort_values(
        by="Accuracy",
        ascending=False
    )
    .reset_index(drop=True)
)

accuracy_ranking

,Model,Accuracy,Precision,Recall,F1 Score,Balanced Accuracy
0,Random Forest,0.836054,0.703704,0.660428,0.681379,0.779972
1,Improved eLCS,0.768630,0.541522,0.836898,0.657563,0.790430
2,Decision Tree,0.761533,0.551913,0.540107,0.545946,0.690826
3,Logistic Regression,0.739532,0.505942,0.796791,0.618899,0.757816

In [4]:
f1_ranking = (
    model_comparison_results
    .sort_values(
        by="F1 Score",
        ascending=False
    )
    .reset_index(drop=True)
)

f1_ranking

,Model,Accuracy,Precision,Recall,F1 Score,Balanced Accuracy
0,Random Forest,0.836054,0.703704,0.660428,0.681379,0.779972
1,Improved eLCS,0.768630,0.541522,0.836898,0.657563,0.790430
2,Logistic Regression,0.739532,0.505942,0.796791,0.618899,0.757816
3,Decision Tree,0.761533,0.551913,0.540107,0.545946,0.690826

In [5]:
recall_ranking = (
    model_comparison_results
    .sort_values(
        by="Recall",
        ascending=False
    )
    .reset_index(drop=True)
)

recall_ranking

,Model,Accuracy,Precision,Recall,F1 Score,Balanced Accuracy
0,Improved eLCS,0.768630,0.541522,0.836898,0.657563,0.790430
1,Logistic Regression,0.739532,0.505942,0.796791,0.618899,0.757816
2,Random Forest,0.836054,0.703704,0.660428,0.681379,0.779972
3,Decision Tree,0.761533,0.551913,0.540107,0.545946,0.690826

## 4. Experimental Findings

In [6]:
from pathlib import Path

evaluation_dir = Path(
    "../results/experimental_evaluation"
)

evaluation_dir.mkdir(
    parents=True,
    exist_ok=True
)

accuracy_ranking.to_csv(
    evaluation_dir / "accuracy_ranking.csv",
    index=False
)

f1_ranking.to_csv(
    evaluation_dir / "f1_ranking.csv",
    index=False
)

recall_ranking.to_csv(
    evaluation_dir / "recall_ranking.csv",
    index=False
)

print("Experimental rankings exported.")

Experimental rankings exported.

## 5. Complete Six-Model Comparison

In [9]:
import pandas as pd

raw_lcs_metrics = pd.read_csv(
    "../results/baseline/baseline_metrics.csv"
)

preprocessed_lcs_metrics = pd.read_csv(
    "../results/preprocessed_lcs/preprocessed_lcs_metrics.csv"
)

improved_lcs_metrics = pd.read_csv(
    "../results/improved_lcs/improved_lcs_metrics.csv"
)

conventional_metrics = pd.read_csv(
    "../results/model_comparison/model_comparison_results.csv"
)

print("All model results loaded successfully.")

display(raw_lcs_metrics)
display(preprocessed_lcs_metrics)
display(improved_lcs_metrics)
display(conventional_metrics)

All model results loaded successfully.

,model,accuracy,precision,recall,f1_score,balanced_accuracy,training_time_seconds,roc_auc,pr_auc
0,Original eLCS,0.806955,0.696154,0.483957,0.570978,0.703814,28.810128,0.827712,0.657853

,Model,Accuracy,Precision,Recall,F1 Score,Balanced Accuracy
0,Original eLCS on Preprocessed Data,0.767921,0.542039,0.81016,0.649518,0.781409

              Metric  Improved eLCS
0           Accuracy       0.768630
1          Precision       0.541522
2             Recall       0.836898
3           F1 Score       0.657563
4  Balanced Accuracy       0.790430

,Model,Accuracy,Precision,Recall,F1 Score,Balanced Accuracy
0,Improved eLCS,0.768630,0.541522,0.836898,0.657563,0.790430
1,Logistic Regression,0.777857,0.552137,0.863636,0.673618,0.805248
2,Decision Tree,0.761533,0.551913,0.540107,0.545946,0.690826
3,Random Forest,0.836054,0.703704,0.660428,0.681379,0.779972

In [10]:
raw_lcs_row = pd.DataFrame({
    "Model": ["Original eLCS on Minimally Processed Data"],
    "Accuracy": [raw_lcs_metrics["accuracy"].iloc[0]],
    "Precision": [raw_lcs_metrics["precision"].iloc[0]],
    "Recall": [raw_lcs_metrics["recall"].iloc[0]],
    "F1 Score": [raw_lcs_metrics["f1_score"].iloc[0]],
    "Balanced Accuracy": [
        raw_lcs_metrics["balanced_accuracy"].iloc[0]
    ]
})

improved_lcs_row = pd.DataFrame({
    "Model": ["Improved eLCS"],
    "Accuracy": [
        improved_lcs_metrics.loc[
            improved_lcs_metrics["Metric"] == "Accuracy",
            "Improved eLCS"
        ].iloc[0]
    ],
    "Precision": [
        improved_lcs_metrics.loc[
            improved_lcs_metrics["Metric"] == "Precision",
            "Improved eLCS"
        ].iloc[0]
    ],
    "Recall": [
        improved_lcs_metrics.loc[
            improved_lcs_metrics["Metric"] == "Recall",
            "Improved eLCS"
        ].iloc[0]
    ],
    "F1 Score": [
        improved_lcs_metrics.loc[
            improved_lcs_metrics["Metric"] == "F1 Score",
            "Improved eLCS"
        ].iloc[0]
    ],
    "Balanced Accuracy": [
        improved_lcs_metrics.loc[
            improved_lcs_metrics["Metric"] == "Balanced Accuracy",
            "Improved eLCS"
        ].iloc[0]
    ]
})

conventional_only = conventional_metrics[
    conventional_metrics["Model"] != "Improved eLCS"
].copy()

complete_model_comparison = pd.concat(
    [
        raw_lcs_row,
        preprocessed_lcs_metrics,
        improved_lcs_row,
        conventional_only
    ],
    ignore_index=True
)

complete_model_comparison

,Model,Accuracy,Precision,Recall,F1 Score,Balanced Accuracy
0,Original eLCS on Minimally Processed Data,0.806955,0.696154,0.483957,0.570978,0.703814
1,Original eLCS on Preprocessed Data,0.767921,0.542039,0.810160,0.649518,0.781409
2,Improved eLCS,0.768630,0.541522,0.836898,0.657563,0.790430
3,Logistic Regression,0.777857,0.552137,0.863636,0.673618,0.805248
4,Decision Tree,0.761533,0.551913,0.540107,0.545946,0.690826
5,Random Forest,0.836054,0.703704,0.660428,0.681379,0.779972

In [12]:
complete_model_comparison.to_csv(
    "../results/experimental_evaluation/"
    "complete_six_model_comparison.csv",
    index=False
)

print("Complete six-model comparison exported.")

Complete six-model comparison exported.

## 6. Statistical Comparison

In [13]:
improved_predictions_data = pd.read_csv(
    "../results/improved_lcs/improved_lcs_predictions.csv"
)

conventional_predictions_data = pd.read_csv(
    "../results/model_comparison/"
    "conventional_model_predictions.csv"
)

actual_target = conventional_predictions_data[
    "actual_target"
].to_numpy()

improved_predictions = improved_predictions_data[
    "predicted_target"
].to_numpy()

random_forest_predictions = conventional_predictions_data[
    "random_forest_prediction"
].to_numpy()

print("Actual targets:", len(actual_target))
print("Improved eLCS predictions:", len(improved_predictions))
print("Random Forest predictions:", len(random_forest_predictions))

Actual targets: 1409
Improved eLCS predictions: 1409
Random Forest predictions: 1409

In [14]:
from scipy.stats import binomtest

improved_correct = (
    improved_predictions == actual_target
)

random_forest_correct = (
    random_forest_predictions == actual_target
)

improved_only_correct = (
    improved_correct
    & ~random_forest_correct
).sum()

random_forest_only_correct = (
    random_forest_correct
    & ~improved_correct
).sum()

discordant_total = (
    improved_only_correct
    + random_forest_only_correct
)

print(
    "Improved eLCS only correct:",
    improved_only_correct
)

print(
    "Random Forest only correct:",
    random_forest_only_correct
)

print(
    "Total discordant predictions:",
    discordant_total
)

if discordant_total > 0:
    mcnemar_result = binomtest(
        k=min(
            improved_only_correct,
            random_forest_only_correct
        ),
        n=discordant_total,
        p=0.5,
        alternative="two-sided"
    )

    print(
        "Exact McNemar p-value:",
        mcnemar_result.pvalue
    )
else:
    print(
        "McNemar test could not be performed because "
        "there were no discordant predictions."
    )

Improved eLCS only correct: 73
Random Forest only correct: 168
Total discordant predictions: 241
Exact McNemar p-value: 8.559183350874963e-10